### ISSUE TITLE
vagrant suspend fails

### ISSUE THREAD

**Issue by osteffich** [wvuweb/hammer-vm#1]
vagrant suspend fails - port is already in use.

```
The command "cd /srv/hammer/hammer && ruby hammer_server.rb --daemon 1" returned a failed exit code. The
error output is shown below:

stdin: is not a tty
[2015-02-28 00:52:58] INFO  WEBrick 1.3.1
[2015-02-28 00:52:58] INFO  ruby 1.9.3 (2014-10-27) [i686-linux]
[2015-02-28 00:52:58] WARN  TCPServer Error: Address already in use - bind(2)
[2015-02-28 00:52:58] WARN  TCPServer Error: Address already in use - bind(2)
/var/lib/gems/1.9.1/gems/webrick-1.3.1/lib/webrick/utils.rb:85:in `initialize': Address already in use - bind(2) (Errno::EADDRINUSE)
    from /var/lib/gems/1.9.1/gems/webrick-1.3.1/lib/webrick/utils.rb:85:in `new'
    from /var/lib/gems/1.9.1/gems/webrick-1.3.1/lib/webrick/utils.rb:85:in `block in create_listeners'
    from /var/lib/gems/1.9.1/gems/webrick-1.3.1/lib/webrick/utils.rb:82:in `each'
    from /var/lib/gems/1.9.1/gems/webrick-1.3.1/lib/webrick/utils.rb:82:in `create_listeners'
    from /var/lib/gems/1.9.1/gems/webrick-1.3.1/lib/webrick/server.rb:82:in `listen'
    from /var/lib/gems/1.9.1/gems/webrick-1.3.1/lib/webrick/server.rb:70:in `initialize'
    from /var/lib/gems/1.9.1/gems/webrick-1.3.1/lib/webrick/httpserver.rb:45:in `initialize'
    from hammer_server.rb:122:in `new'
    from hammer_server.rb:122:in `<main>'
```

**Comment by zeroedin** [comment]
This is still an open issue.  Can not currently use `vagrant suspend` and `vagrant resume`
