### ISSUE TITLE
certificate verification failed:  stash.development.wvu.edu/scm/cst/code.git

### ISSUE THREAD

**Issue by architarious** [wvuweb/hammer-vm#5]
via powershell: 

E:\hammer-vm [master +0 ~1 -0]> vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Checking if box 'ubuntu/trusty32' is up to date...
==> default: A newer version of the box 'ubuntu/trusty32' is available! You currently
==> default: have version '14.04'. The latest is version '20150814.0.0'. Run
==> default: `vagrant box update` to update.
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
==> default: Forwarding ports...
    default: 2000 => 2000 (adapter 1)
    default: 22 => 2222 (adapter 1)
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 127.0.0.1:2222
    default: SSH username: vagrant
    default: SSH auth method: private key
    default: Warning: Connection timeout. Retrying...
    default: Warning: Remote connection disconnect. Retrying...
    default: Warning: Remote connection disconnect. Retrying...
    default: Warning: Connection timeout. Retrying...
    default: Warning: Connection timeout. Retrying...
    default: Warning: Connection timeout. Retrying...
    default: Warning: Connection timeout. Retrying...
    default: Warning: Connection timeout. Retrying...
    default: Warning: Connection timeout. Retrying...
    default: Warning: Connection timeout. Retrying...
    default: Warning: Connection timeout. Retrying...
    default: Warning: Connection timeout. Retrying...
    default: Warning: Connection timeout. Retrying...
    default: Warning: Connection timeout. Retrying...
    default: Warning: Connection timeout. Retrying...
==> default: Machine booted and ready!
==> default: Checking for guest additions in VM...
==> default: Setting hostname...
==> default: Mounting shared folders...
    default: /vagrant => E:/hammer-vm
    default: /srv/cleanslate_themes => E:/cleanslate_themes
==> default: Machine already provisioned. Run `vagrant provision` or use the `--provision`
==> default: to force provisioning. Provisioners marked to run always will still run.
==> default: Running triggers after up...
==> default: Starting Hammer...
==> default: Executing remote command "cd /srv/hammer/hammer && ruby hammer_server.rb --daemon 1"...
==> default: stdin: is not a tty
==> default: /var/lib/gems/1.9.1/gems/git-1.2.8/lib/git/lib.rb:764:in `command'
==> default: :
==> default: git ls-remote   2>&1:fatal: unable to access 'https://stash.development.wvu.edu/scm/cst/code.git/': server
certificate verification failed. CAfile: /etc/ssl/certs/ca-certificates.crt CRLfile: none
==> default:  (
==> default: Git::GitExecuteError
==> default: )
==> default:    from hammer_server.rb:101:in`<main>'
==> default: Remote command execution finished.
The command "cd /srv/hammer/hammer && ruby hammer_server.rb --daemon 1" returned a failed exit code. The
error output is shown below:

stdin: is not a tty
/var/lib/gems/1.9.1/gems/git-1.2.8/lib/git/lib.rb:764:in `command': git ls-remote   2>&1:fatal: unable to access 'https:
//stash.development.wvu.edu/scm/cst/code.git/': server certificate verification failed. CAfile: /etc/ssl/certs/ca-certif
icates.crt CRLfile: none (Git::GitExecuteError)
        from hammer_server.rb:101:in`<main>'

**Comment by architarious** [comment]
Solved, didn't notice that this blog posting had been made: 
http://cleanslatecms.wvu.edu/blog/2015/08/11/hammer-vm-certificate-verification-failure-and-fix

This worked for me.
