### ISSUE TITLE
SSL verify issue on hammer update

### ISSUE THREAD

**Issue by adamjohnson** [wvuweb/hammer-vm#6]
1. Run `hammer-start`.
2. Run `hammer-update`.

It'll blow up and give you this:

``` bash
Bundle complete! 14 Gemfile dependencies, 28 gems now installed.
Use `bundle show [gemname]` to see where a bundled gem is installed.
Restarting Hammer...
/var/lib/gems/1.9.1/gems/git-1.2.8/lib/git/lib.rb:764:in `command': git ls-remote   2>&1:fatal: unable to access 'https://stash.development.wvu.edu/scm/cst/code.git/': server certificate verification failed. CAfile: /etc/ssl/certs/ca-certificates.crt CRLfile: none (Git::GitExecuteError)
    from hammer_server.rb:101:in `<main>'
Finished Upgrade!
```

This command needs run on `hammer-update`:

https://github.com/wvuweb/hammer-vm/blob/master/Vagrantfile#L24

**Comment by zeroedin** [comment]
old issue, closing as inactive no longer an issue.
